-- COMEÇO GUIADO
-- Dados de partida: Tabelas importadas de `dados/clientes.csv`, `planos.csv`, `chamados.csv`, `pagamentos.csv`, `incidentes.csv` e `pedidos.csv`.
-- Use as tabelas já carregadas. Escreva e execute uma consulta por vez; confira as
-- colunas e as linhas retornadas antes de seguir.

-- JOINs
--
-- Arquivo preparado a partir do roadmap.
-- Nenhuma atividade foi resolvida neste arquivo.
--
-- ENUNCIADOS
-- NÚCLEO ESSENCIAL
-- 1. [ ] Crie tabelas `clientes`, `planos`, `chamados` e `pagamentos` com chaves primárias e estrangeiras; importe dados do kit.
-- 2. [ ] Escreva um `LEFT JOIN` para encontrar clientes sem pagamentos e um anti-join para planos sem clientes.
-- 3. [ ] Crie um caso muitos-para-muitos acidental duplicando chaves; meça como isso infla soma de mensalidade.
-- PRÁTICA OBRIGATÓRIA
-- 4. [ ] Corrija o problema agregando antes do join ou validando cardinalidade.
-- 5. [ ] Desenhe em Mermaid ou texto o relacionamento entre as quatro tabelas e anote a granularidade de cada uma.
-- 6. [ ] Conte linhas e clientes distintos antes e depois do join com pagamentos para revelar qualquer multiplicação de registros.
--
-- Escreva sua solução abaixo desta linha.
