-- COMEÇO GUIADO
-- Dados de partida: Tabelas importadas de `dados/clientes.csv`, `planos.csv`, `chamados.csv`, `pagamentos.csv`, `incidentes.csv` e `pedidos.csv`.
-- Use as tabelas já carregadas. Escreva e execute uma consulta por vez; confira as
-- colunas e as linhas retornadas antes de seguir.

-- Cohorts e retenção
--
-- Arquivo preparado a partir do roadmap.
-- Nenhuma atividade foi resolvida neste arquivo.
--
-- ENUNCIADOS
-- NÚCLEO ESSENCIAL
-- 1. Defina coorte como mês da primeira compra ou ativação; calcule o mês inicial de cada cliente.
-- 2. Crie tabela com `cohort_month`, `period_number`, clientes ativos e taxa de retenção.
-- 3. Monte matriz de retenção do mês 0 ao mês 5 e valide manualmente uma coorte pequena com cinco clientes.
-- PRÁTICA OBRIGATÓRIA
-- 4. Compare retenção por canal de aquisição ou plano.
-- 5. Escreva três conclusões e uma cautela sobre coortes pequenas.
--
-- Escreva sua solução abaixo desta linha.
